VermilionCity_House1_Text_GuruIntro::
    .string "Hah! A challenger!\p"
    .string "Let's see if you're worthy\n"
    .string "of calling yourself a fisher!$"

VermilionCity_House1_Text_GuruDefeated::
    .string "You got me!\n"
    .string "You have true talent!$"

VermilionCity_House1_Text_GuruPostBattle::
    .string "Fishing and battling…\p"
    .string "Both take patience and skill.\n"
    .string "You have both, young one.$"